# Build commands

# Production build command
[build]
  command = "npm run build"

# Non-production build command
[context.deploy-preview]
  command = "npm run staging"

[context.branch-deploy]
  command = "npm run staging"


# Redirects

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://tempertemper.netlify.com/*"
  to = "https://tempertemper.net/:splat"
  status = 301
  force = true


# Blog to Resources redirects

[[redirects]]
  from = "/2012-05-30-freeagent"
  to = "/blog/freeagent"
  status = 301
  force = true

[[redirects]]
  from = "/blog/why-you-need-a-privacy-policy"
  to = "/resources/why-you-need-a-privacy-policy"
  status = 301
  force = true

[[redirects]]
  from = "/blog/google-gets-serious-about-ssl"
  to = "/resources/google-gets-serious-about-ssl"
  status = 301
  force = true

[[redirects]]
  from = "/blog/what-search-engines-want"
  to = "/resources/what-search-engines-want"
  status = 301
  force = true

[[redirects]]
  from = "/blog/what-you-see-isnt-what-you-get"
  to = "/resources/what-you-see-isnt-what-you-get"
  status = 301
  force = true

[[redirects]]
  from = "/blog/ssl-for-everyone"
  to = "/resources/ssl-for-everyone"
  status = 301
  force = true

[[redirects]]
  from = "/blog/website-updates-and-avoiding-content-loss"
  to = "/resources/website-updates-and-avoiding-content-loss"
  status = 301
  force = true

[[redirects]]
  from = "/blog/types-of-email-and-when-to-use-each"
  to = "/resources/types-of-email-and-when-to-use-each"
  status = 301
  force = true

[[redirects]]
  from = "/blog/regular-backups-are-important"
  to = "/resources/regular-backups-are-important"
  status = 301
  force = true

[[redirects]]
  from = "/blog/edit-your-blog-posts-off-line"
  to = "/resources/edit-your-blog-posts-off-line"
  status = 301
  force = true

[[redirects]]
  from = "/blog/design-and-build-for-the-worst-case-scenario"
  to = "/resources/design-and-build-for-the-worst-case-scenario"
  status = 301
  force = true

[[redirects]]
  from = "/blog/look-after-your-domain-name"
  to = "/resources/look-after-your-domain-name"
  status = 301
  force = true

[[redirects]]
  from = "/blog/regular-website-maintenance"
  to = "/resources/regular-website-maintenance"
  status = 301
  force = true

[[redirects]]
  from = "/blog/website-video"
  to = "/resources/website-video"
  status = 301
  force = true

[[redirects]]
  from = "/blog/bookmark-icons"
  to = "/resources/bookmark-icons"
  status = 301
  force = true

[[redirects]]
  from = "/blog/giving-social-media-the-right-information"
  to = "/resources/giving-social-media-the-right-information"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tidy-up-your-sites-addresses-for-search"
  to = "/resources/tidy-up-your-sites-addresses-for-search"
  status = 301
  force = true

[[redirects]]
  from = "/blog/mobile-friendly-markers"
  to = "/resources/mobile-friendly-markers"
  status = 301
  force = true

[[redirects]]
  from = "/blog/the-three-golden-rules-of-sending-marketing-emails"
  to = "/resources/the-three-golden-rules-of-sending-marketing-emails"
  status = 301
  force = true

[[redirects]]
  from = "/blog/displaying-an-email-address-on-your-website"
  to = "/resources/displaying-an-email-address-on-your-website"
  status = 301
  force = true

[[redirects]]
  from = "/blog/what-is-meta-data"
  to = "/resources/what-is-meta-data"
  status = 301
  force = true

[[redirects]]
  from = "/blog/webfonts"
  to = "/resources/webfonts"
  status = 301
  force = true

[[redirects]]
  from = "/blog/how-the-web-works"
  to = "/resources/how-the-web-works"
  status = 301
  force = true

[[redirects]]
  from = "/blog/what-is-ssl-and-is-it-worth-the-bother"
  to = "/resources/what-is-ssl-and-is-it-worth-the-bother"
  status = 301
  force = true

[[redirects]]
  from = "/blog/image-cropping"
  to = "/resources/image-cropping"
  status = 301
  force = true

[[redirects]]
  from = "/blog/why-i-changed-my-baseline"
  to = "/resources/why-i-changed-my-baseline"
  status = 301
  force = true

[[redirects]]
  from = "/blog/page-titles"
  to = "/resources/page-titles"
  status = 301
  force = true

[[redirects]]
  from = "/blog/the-great-unknown"
  to = "/resources/the-great-unknown"
  status = 301
  force = true

[[redirects]]
  from = "/blog/taking-a-break-without-neglecting-your-business"
  to = "/resources/taking-a-break-without-neglecting-your-business"
  status = 301
  force = true

[[redirects]]
  from = "/blog/are-you-living-in-the-past"
  to = "/resources/are-you-living-in-the-past"
  status = 301
  force = true

[[redirects]]
  from = "/blog/how-to-write-a-link-using-markdown"
  to = "/resources/how-to-write-a-link-using-markdown"
  status = 301
  force = true

[[redirects]]
  from = "/blog/how-to-write-a-link"
  to = "/resources/how-to-write-a-link"
  status = 301
  force = true

[[redirects]]
  from = "/blog/password-security"
  to = "/resources/password-security"
  status = 301
  force = true

[[redirects]]
  from = "/blog/how-headings-work"
  to = "/resources/how-headings-work"
  status = 301
  force = true

[[redirects]]
  from = "/blog/what-is-markdown"
  to = "/resources/what-is-markdown"
  status = 301
  force = true

[[redirects]]
  from = "/blog/markdown-cheatsheet"
  to = "/resources/markdown-cheatsheet"
  status = 301
  force = true

[[redirects]]
  from = "/blog/how-can-twitter-help-my-business"
  to = "/resources/how-can-twitter-help-my-business"
  status = 301
  force = true


[[redirects]]
  from = "/blog/ios-email-set-up"
  to = "/resources/ios-email-set-up"
  status = 301
  force = true

[[redirects]]
  from = "/blog/android-email-set-up"
  to = "/resources/android-email-set-up"
  status = 301
  force = true

[[redirects]]
  from = "/blog/contact-forms"
  to = "/resources/contact-forms"
  status = 301
  force = true

[[redirects]]
  from = "/blog/do-i-need-a-cms"
  to = "/resources/do-i-need-a-cms"
  status = 301
  force = true

[[redirects]]
  from = "/blog/should-you-go-responsive"
  to = "/resources/should-you-go-responsive"
  status = 301
  force = true

[[redirects]]
  from = "/blog/responsive"
  to = "/resources/should-you-go-responsive"
  status = 301
  force = true

[[redirects]]
  from = "/blog/disability-on-the-web"
  to = "/resources/disability-on-the-web"
  status = 301
  force = true

[[redirects]]
  from = "/blog/calls-to-action"
  to = "/resources/calls-to-action"
  status = 301
  force = true

[[redirects]]
  from = "/blog/links-make-the-web-go-round"
  to = "/resources/links-make-the-web-go-round"
  status = 301
  force = true

[[redirects]]
  from = "/blog/making-the-most-of-your-blog-posts"
  to = "/resources/making-the-most-of-your-blog-posts"
  status = 301
  force = true

[[redirects]]
  from = "/blog/image-alt-text"
  to = "/resources/image-alt-text"
  status = 301
  force = true

[[redirects]]
  from = "/blog/little-by-little"
  to = "/resources/little-by-little"
  status = 301
  force = true

[[redirects]]
  from = "/blog/like-follow-no-thanks"
  to = "/resources/like-follow-no-thanks"
  status = 301
  force = true

[[redirects]]
  from = "/blog/google-places"
  to = "/resources/google-places"
  status = 301
  force = true

[[redirects]]
  from = "/blog/cms-updates"
  to = "/resources/cms-updates"
  status = 301
  force = true

[[redirects]]
  from = "/blog/page-descriptions"
  to = "/resources/page-descriptions"
  status = 301
  force = true

[[redirects]]
  from = "/blog/reduce-spam"
  to = "/resources/reduce-spam"
  status = 301
  force = true

[[redirects]]
  from = "/blog/domain-name-renewals"
  to = "/resources/domain-name-renewals"
  status = 301
  force = true

[[redirects]]
  from = "/blog/google-history-and-your-ranking"
  to = "/resources/google-history-and-your-ranking"
  status = 301
  force = true

[[redirects]]
  from = "/blog/facebook-business-pages"
  to = "/resources/facebook-business-pages"
  status = 301
  force = true

[[redirects]]
  from = "/blog/writing-your-website"
  to = "/resources/writing-your-website"
  status = 301
  force = true

[[redirects]]
  from = "/blog/older-browsers"
  to = "/resources/older-browsers"
  status = 301
  force = true

[[redirects]]
  from = "/blog/why-do-i-need-a-website"
  to = "/resources/why-do-i-need-a-website"
  status = 301
  force = true

[[redirects]]
  from = "/blog/branded-email"
  to = "/resources/branded-email"
  status = 301
  force = true

[[redirects]]
  from = "/blog/keywords"
  to = "/resources/keywords"
  status = 301
  force = true

[[redirects]]
  from = "/blog/do-i-need-a-mobile-website"
  to = "/resources/do-i-need-a-mobile-website"
  status = 301
  force = true

[[redirects]]
  from = "/blog/whats-in-a-browser"
  to = "/resources/whats-in-a-browser"
  status = 301
  force = true

[[redirects]]
  from = "/blog/why-should-i-blog"
  to = "/resources/why-should-i-blog"
  status = 301
  force = true

[[redirects]]
  from = "/blog/google-whats-the-fuss"
  to = "/resources/google-whats-the-fuss"
  status = 301
  force = true

[[redirects]]
  from = "/blog/qr-readers"
  to = "/resources/qr-readers"
  status = 301
  force = true

[[redirects]]
  from = "/blog/the-types-of-email"
  to = "/resources/the-types-of-email"
  status = 301
  force = true

[[redirects]]
  from = "/blog/google-analytics"
  to = "/resources/google-analytics"
  status = 301
  force = true

[[redirects]]
  from = "/blog/category/apps"
  to = "/category/tools"
  status = 301
  force = true

[[redirects]]
  from = "/blog/category/tools"
  to = "/category/tools"
  status = 301
  force = true

[[redirects]]
  from = "/blog/category/design-and-build"
  to = "/category/design"
  status = 301
  force = true

[[redirects]]
  from = "/resources/category/content"
  to = "/category/content"
  status = 301
  force = true

[[redirects]]
  from = "/blog/category/gathering-content"
  to = "/category/content"
  status = 301
  force = true

[[redirects]]
  from = "/blog/category/ongoing-work"
  to = "/blog/"
  status = 301
  force = true

[[redirects]]
  from = "/resources/category/updates"
  to = "/category/website-admin"
  status = 301
  force = true

[[redirects]]
  from = "/blog/category/opinion"
  to = "/blog/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/category/planning"
  to = "/category/website-admin"
  status = 301
  force = true

[[redirects]]
  from = "/resources/category/admin"
  to = "/rcategory/website-admin/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/category/resources"
  to = "/resources/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/category/set-up"
  to = "/resources/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/accessibility"
  to = "/category/accessibility"
  status = 301
  force = true

[[redirects]]
  from = "/resources/category/accessibility"
  to = "/category/accessibility"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/backup"
  to = "/resources/"
  status = 301
  force = true

[[redirects]]
  from = "/resources/category/updates"
  to = "/resources/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/browsers"
  to = "/category/accessibility"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/cms"
  to = "/category/content"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/content"
  to = "/category/content"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/core-concepts"
  to = "/category/performance"
  status = 301
  force = true

[[redirects]]
  from = "/resources/category/performance"
  to = "/category/performance"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/design"
  to = "/category/design"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/engagement"
  to = "/category/marketing"
  status = 301
  force = true

[[redirects]]
  from = "/resources/category/marketing"
  to = "/category/marketing"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/focus"
  to = "/category/content"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/gadgets"
  to = "/category/tools"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/google"
  to = "/category/search"
  status = 301
  force = true

[[redirects]]
  from = "/resources/category/search"
  to = "/category/search"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/holidays"
  to = "/category/business"
  status = 301
  force = true

[[redirects]]
  from = "/resources/category/business"
  to = "/category/business"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/images"
  to = "/category/content"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/keeping-in-touch"
  to = "/category/marketing"
  status = 301
  force = true

[[redirects]]
  from = "/resources/category/social-media"
  to = "/category/marketing"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/maintenance"
  to = "/category/website-admin"
  status = 301
  force = true

[[redirects]]
  from = "/resources/category/updates"
  to = "/category/website-admin"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/markdown"
  to = "/category/markdown"
  status = 301
  force = true

[[redirects]]
  from = "/resources/category/markdown"
  to = "/category/markdown"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/marketing"
  to = "/category/marketing"
  status = 301
  force = true

[[redirects]]
  from = "/resources/category/marketing"
  to = "/category/marketing"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/measurement"
  to = "/category/website-admin"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/measurement"
  to = "/category/website-admin"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/meta-data"
  to = "/category/meta-data"
  status = 301
  force = true

[[redirects]]
  from = "/resources/category/meta-data"
  to = "/category/meta-data"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/mobile-friendly"
  to = "/category/search"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/performance"
  to = "/category/performance"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/privacy"
  to = "/category/privacy"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/search"
  to = "/category/search"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/security"
  to = "/category/security"
  status = 301
  force = true

[[redirects]]
  from = "/resources/category/security"
  to = "/category/security"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/seo"
  to = "/category/search"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/social"
  to = "/category/marketing"
  status = 301
  force = true

[[redirects]]
  from = "/resources/category/social-media"
  to = "/category/marketing"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/social-media"
  to = "/category/marketing"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/speed"
  to = "/category/performance"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/twitter"
  to = "/category/marketing"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/video"
  to = "/category/content"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/work-life-balance"
  to = "/category/business"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/writing"
  to = "/category/content"
  status = 301
  force = true


# Other rewites
[[redirects]]
  from = "/legal/"
  to = "/privacy-policy"
  status = 301
  force = true

[[redirects]]
  from = "/legal/terms"
  to = "/terms"
  status = 301
  force = true

[[redirects]]
  from = "/legal/privacy-policy"
  to = "/privacy-policy"
  status = 301
  force = true

[[redirects]]
  from = "/blog/rss"
  to = "/feeds/main.xml"
  status = 301
  force = true

[[redirects]]
  from = "/feeds/blog/rss.xml"
  to = "/feeds/main.xml"
  status = 301
  force = true

[[redirects]]
  from = "/feeds/blog/feed.xml"
  to = "/feeds/main.xml"
  status = 301
  force = true

[[redirects]]
  from = "/blog/json"
  to = "/feeds/main.json"
  status = 301
  force = true

[[redirects]]
  from = "/feeds/blog/feed.json"
  to = "/feeds/main.json"
  status = 301
  force = true

[[redirects]]
  from = "/error"
  to = "/404"
  status = 301
  force = true

[[redirects]]
  from = "/assets/img/tempertemper-web-design-logo-facebook.jpg"
  to = "/assets/img/summary.png"
  status = 301
  force = true

[[redirects]]
  from = "/assets/images/tempertemper-web-design-logo-facebook.jpg"
  to = "/assets/img/summary.png"
  status = 301
  force = true

[[redirects]]
  from = "/cms/addons/feathers/tempertemper/*"
  to = "/404"
  status = 301
  force = true

[[redirects]]
  from = "/apple-touch-icon-precomposed.png"
  to = "/assets/img/icons/apple-touch-icon-180x180.png"
  status = 301
  force = true

[[redirects]]
  from = "/apple-touch-icon.png"
  to = "/assets/img/icons/apple-touch-icon-180x180.png"
  status = 301
  force = true

[[redirects]]
  from = "/blog/free-security-updates"
  to = "/blog/"
  status = 301
  force = true

[[redirects]]
  from = "/testimonials/jonny-p%C3%A9nzes-underhill"
  to = "/testimonials/jonny-penzes-underhill"
  status = 301
  force = true

[[redirects]]
  from = "/resources/types-of-email-and-when-to-use%C2%A0each"
  to = "/resources/types-of-email-and-when-to-use-each"
  status = 301
  force = true

[[redirects]]
  from = "/blog/discrimination-on-the-web"
  to = "/resources/disability-on-the-web"
  status = 301
  force = true

[[redirects]]
  from = "/blog/dropbox-%E2%80%93-my-most-useful-app"
  to = "/blog/dropbox-my-most-useful-app"
  status = 301
  force = true

[[redirects]]
  from = "/blog/blog/thoughts-on-3d-touch"
  to = "/blog/thoughts-on-3d-touch"
  status = 301
  force = true

[[redirects]]
  from = "/resources/contact"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/about/colophon"
  to = "/colophon"
  status = 301
  force = true

[[redirects]]
  from = "/resources/%5D%28/blog/password-security%29"
  to = "/resources/password-security"
  status = 301
  force = true

[[redirects]]
  from = "/cms/resources/blog/internet-explorer-icon.png"
  to = "/assets/img/summary.png"
  status = 301
  force = true


# Spam rewrites
[[redirects]]
  from = "/wp-login.php"
  to = "/404"
  status = 301
  force = true

[[redirects]]
  from = "/blog/wp-login.php"
  to = "/404"
  status = 301
  force = true

[[redirects]]
  from = "/resources/wp-login.php"
  to = "/404"
  status = 301
  force = true

[[redirects]]
  from = "/.git/HEAD"
  to = "/404"
  status = 301
  force = true

[[redirects]]
  from = "/post.php"
  to = "/blog/"
  status = 301
  force = true

[[redirects]]
  from = "/this-url-does-not-exist"
  to = "/404"
  status = 301
  force = true

[[redirects]]
  from = "/index2"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/..."
  to = "/"
  status = 301
  force = true


# External rewrites
[[redirects]]
  from = "/youtube"
  to = "https://www.youtube.com/tempertemper"
  status = 301
  force = true
